name: doxygen-deploy

on:
  push:
    branches: [ main ]   # triggers whenever main is pushed

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Doxygen and Graphviz
        run: sudo apt-get install -y doxygen graphviz

      - name: Run Doxygen
        working-directory: ${{ github.workspace }}
        run: doxygen Doxyfile

      - name: Disable Jekyll for GitHub Pages
        run: touch ${{ github.workspace }}/html/.nojekyll

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          branch: gh-pages
          folder: ${{ github.workspace }}/html
          token: ${{ secrets.GH_PAT }}
